terminal.h
terminal_base.h

**Summary:**
* Mark some functions `inline` to avoid multiple definitions error.
* Change some function signatures to use `size_t` instead of `int`
* Change how escape some codes are represented to avoid build warnings.
* Be more explicit about casting between different `char` types.
* Fixes #1
**Comments**:
* You might still need to mark more functions `inline`. When I import your files into my project, I am moving many function implementations into a `.cpp` file.
* It looks like my editor re-indented `print_rect` for me.  Sorry about that style change. Have you considered using a `.clang-format` file to enforce formatting choices?

Attempt to eliminate some MSVC /W build warnings.

---

examples/menu_window.cpp
terminal.h

I finally figured out how to really simplify the code. Now it is short and concise, and does not do any redundant operation.

Simplify codepoint_to_utf8()

---

terminal.h

This prevents issues with comparing (un)signed char with integers.

Convert integers to hexadecimal characters

---

cpp-terminal/terminal_base.h

Fixes #35.
I actually do not like this. The fix looks ugly, and what if the user has a `B0` macro, then this would undefine it.
I think the solution is to split the code into a header and a cpp file. And import the `termios.h` in the cpp file, that way it won't collide with anything.
@KineticTheory let me know what you think.

Undefine colliding defines

---

cpp-terminal/terminal.h

Previously it could sometimes fail if the response from the terminal was
not complete or it contained user input first. Now we find the terminal
response in the input and drop the rest. All corner cases should be
covered by now.

Make get_cursor_position() more robust

---

cpp-terminal/terminal_base.h

Previously it raised an exception, but it seems a better API is to
return false if the terminal is not connected to a terminal.

Make get_term_size() return false for nontty

---

cpp-terminal/terminal_base.h

When not connected to a terminal, we are in a blocking mode. It is still
helpful to make `read_raw()` work, so that one can feed input to the
application by redirecting stdin, for example at a CI.

Make read_raw() work when not connected to a tty

---

cpp-terminal/terminal.h

In the prompt, instead of pushing back the `ctrl + d` key at the end of the input, I remove any previous input and push this key only.
Same for `ctrl + c`.
Please tell me what you think @certik :) This behavior sounds right to me but I am not sure this is the best way of doing it.

Prompt: Discard any input on ctrl+c or ctrl+u

---

CMakeLists.txt
ci/citest.sh
examples/CMakeLists.txt
examples/kilo.cpp

Hello,
it's me again, this time with some small changes in the cmake. I have added options to skip the building of the example projects to speed up compile time in xternal projects and remove the targets from visual studio codes target list. I have also enabled extended compile features on the example programs (it's not possible for the cpp-terminal target as it has only headers). Feel free to request changes!
Cheers!

Improved CMake

---

cpp-terminal/terminal.h
examples/colors.cpp
examples/kilo.cpp

Just the last small things from #68 I didn't wanted to throw away. Nothing big.

really small optical changes

---

cpp-terminal/terminal.h
examples/kilo.cpp

This function moves the write() function outside of the class into the Term:: namespace as disqussed in #81.

moved write function outside of class

---

cpp-terminal/terminal.h
examples/CMakeLists.txt
examples/colors.cpp
examples/menu_window_24bit.cpp

This pull-request adds `color24()`, a small addition to the `color()` function to use 24bit true color on supported terminals like discussed in #69.

24bit colors

---

CMakeLists.txt
cpp-terminal/terminal.h
cpp-terminal/terminal_base.h
examples/menu_window.cpp
examples/menu_window_24bit.cpp
examples/prompt.cpp
test-standalone/CMakeLists.txt

Manual merge of current cpp-terminal on LFortran and the main repo version. I confirmed this compiles in LFortran and things generally seem to work but the REPL test fails (runtime_error: tcgetattr() failed is thrown). Perhaps some testing of the examples here will reveal the problem.

Merge of LFortran cpp-terminal changes

---

cpp-terminal/terminal.h
examples/colors.cpp

This add some improvements and additions:
- added `clear_screen()` and `clear_screen_buffer()`
- renamed `style::rblink` to `style::blink_rapid`
- added `style::overline`
- moved bright colors into fg / bg because it's the same but bright
- renamed some colors as white is not grey but bright black is
- split `color24` to make is easier to read in code and to make it inline instead of static

Small usability improvements

---

cpp-terminal/terminal.h

As introduced in #64 and implemented in #68: This pull-request tries to simplify the get_cursor_position() function. The code should be checked of logic mistakes. I have tried to just change the code, but don't touch the logic at all. I hope it's still intakt!

simplified for loop

---

README.md

Add two more general TUI libraries to the list of similar projects. Both are present in Awesome C++ in the same category as cpp-terminal

two more similar projects: FTXUI and imtui

---

examples/prompt.cpp

Noticed this error when running the prompt example, just hitting enter will throw an out of range exception:
```
terminate called after throwing an instance of 'std::out_of_range'                                                                                                                   1,1   ]
what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 1)
gdb:
0x00005555555575da in determine_completeness (command="\n") at /home/awvwgk/projects/src/git/cpp-terminal/examples/prompt.cpp:15
```

Out of range error in prompt example for ENTER input

---

cpp-terminal/base.cpp
cpp-terminal/base.hpp

This PR removes the `get_term_size_slow()` function. I tried to fix it because it wouldn't compile after the header changes, but it seems like the function is generally not working. I tried a very old commit, but there this function was already broken. Could be an issue with my terminal though, but Kitty and the vscode terminal both just show some characters and even after minutes nothing happens. If you want to keep the function nevertheless, you need to help on this one @certik.
Fixes #115.

removed get_term_size_slow()

---

cpp-terminal/base.cpp
cpp-terminal/base.hpp
cpp-terminal/prompt.cpp
examples/keys.cpp
examples/kilo.cpp
examples/menu.cpp
examples/menu_window.cpp
examples/menu_window_24bit.cpp
examples/prompt_multiline.cpp

This PR fixes the screen clearing if the given terminal is not supporting the `save_screen()` function (The linux VGA/TTY console for example). I have also added an option to automatically hide the cursor.

Ported some fixes 

---

cpp-terminal/private/platform.cpp
cpp-terminal/private/platform.hpp
cpp-terminal/prompt.hpp

Hi,
This changes allow to remove the #undef ERROR and to move most of the platform hearders to the cpp

Supress undef ERROR

---

cpp-terminal/base.cpp
cpp-terminal/base.hpp
cpp-terminal/private/conversion.hpp
cpp-terminal/private/platform.cpp
cpp-terminal/private/platform.hpp
cpp-terminal/prompt.cpp
cpp-terminal/prompt.hpp
cpp-terminal/window.cpp
cpp-terminal/window.hpp
examples/colors.cpp
examples/keys.cpp
examples/kilo.cpp
examples/menu.cpp
examples/menu_window.cpp
examples/menu_window_24bit.cpp
examples/prompt_multiline.cpp
tests/test-standalone/colors.cpp

This PR implements a unified interface for 4bit / 8bit / 24bit colors and features a few new features.
Implements #190.
Also Implements partly #177, #175.

Implemented new base.hpp structure

---

cpp-terminal/platforms/terminfo.cpp
cpp-terminal/terminfo.hpp

This is fixing #108 by checking if we use the MacOS terminal and convert all to 8bits colors.
ANSICON is detected too and convert all to 4bits (ANSICON do this by itself but we do it by ourself)
Still need to be fixed : old window$ without ANSICON
Windows with ANSICON on `Window$ 7` (It takes centuries to print but....) : 
MacOS terminal (I could not imagine MacOS still use 256colors):
For other terminal we need a terminfo parser and use TERM env variable to have better information but we check for COLORTERM value and fallback as 8bits colors by default

Automatically choose the right palette 

---

cpp-terminal/platforms/CMakeLists.txt
cpp-terminal/platforms/env.cpp
cpp-terminal/platforms/env.hpp
cpp-terminal/platforms/terminal.cpp
cpp-terminal/platforms/terminfo.cpp
cpp-terminal/terminal.cpp
cpp-terminal/terminal.hpp
examples/keys.cpp

This PR fix #248 by doing : 
1) All the exceptions in the destructor are catched inside it to avoid the exception to leak...
2) A message is printed to say the terminal is not in good state with reasons if possible
3) Return EXIT_FAILURE to the parent or the value given by the environment variable CPP_TERMINAL_BADSTATE if it can be casted to int otherwise return the default value (EXIT_FAILURE). It is possible to do:
UNIX :
```bash
./examples/keys ; echo $?
``` 
Windows : 
```cmd
.\examples\keys
echo %errorlevel%
```
to check if the terminal is in good mode.
I think it's the safest way to avoid crash and to let the user know something bad happened and to perform correction if he can/want/should.\
Global variable was impossible because the terminal is destroyed after the main ends so the …

Badstate  (Fix #248)

---

cmake/Warnings.cmake
cpp-terminal/color.cpp
cpp-terminal/platforms/terminal.cpp
cpp-terminal/platforms/terminfo.cpp
cpp-terminal/terminfo.hpp
examples/CMakeLists.txt

Uselegacy fix #241

---

cpp-terminal/exception.hpp
cpp-terminal/platforms/CMakeLists.txt
cpp-terminal/platforms/args.cpp
cpp-terminal/platforms/conversion.cpp
cpp-terminal/platforms/conversion.hpp
cpp-terminal/platforms/env.cpp
cpp-terminal/platforms/exception.cpp
cpp-terminal/platforms/exception.hpp
cpp-terminal/platforms/input.cpp
cpp-terminal/platforms/unicode.cpp
cpp-terminal/platforms/unicode.hpp
examples/CMakeLists.txt
tests/CMakeLists.txt
tests/exception.test.cpp
tests/unicode.test.cpp

`Windows` use UNICODE (`wchar_t` in `utf16`), this PR add a better narrow<->wide converter only for Windows as utf16 is useless on other OS. I added special `WindowsError` exception too to be able to get the string corresponding to `GetLastError()` (converted to utf8 of course). This will allow to have better exceptions on windows without too much trouble. I expect to have one for `errno` too

Windows unicode

---

cpp-terminal/iostream.cpp

I was getting segmentation faults for every example after building with Clang 17.0.6 and after further investigation it seems that the only issue was a typo in the size of the cin_buffer.

Fix Clang 17

---

cpp-terminal/prompt.cpp

Seems to address #404.
For the record - I have no idea what I'm doing in this repo, I just noticed that this was comparing rows to columns and it appears to fix it, it's entirely possible that this isn't the right fix.
Also - does something like this warrant a test?

Fix issue with multiline prompts jumping
